//@host = http://localhost:8080/plusFriends/getUsuarioBancoDados
@host = http://localhost:8080/plusFriends/getUsuarioBancoDados/admin/admin123
//@host = http://localhost:8080/plusFriends/postUsuarioBancoDados
//@host = http://localhost:8080/plusFriends/put/atualizarDtUltLogin


###


{{host}}

###


POST {{host}}
Content-Type: application/json

{
    "nome": "teste",
    "sobrenome": "da silva",
    "sexo": "3",
    "idade": 22,
    "cpf": "123.123.123-00",
    "email": "teste@teste.com",
    "usuario": "tezinho",
    "senha": "tetete123"
}